id: IECA6A4DC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:51:17+00:00'
last_modified: '2022-06-08T08:28:06.207835+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20374
  title: དགྲ་ལྷ་ཟླ་བ་བཟང་པོའི་ཆེད་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '6681':
      image_group_id: I8LS20376
      title: ''
      total_pages: 553
      order: 1
      base_file: 6681.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
